### ISSUE TITLE
Alt Parameters: check consistency of AltParamChoice at compile time

### ISSUE THREAD

**Issue by LnnrtS** [4ms/metamodule#206]
>  I originally had a template parameter, but then we need to add all possible values for the size to the variant, which seemed excessive. It worked everywhere else (using lambda templates for the visits with overloaded sets).
Attempting to create a AltParamChoice with more than 8 position strings will give a compile-time error, though there's no way to stop someone from creating one with 9 positions and the default strings, which would have to be runtime checked or clamped.
The idea is that these are generated by the SVG processing scripts (we have been manually changing these generated files in this branch, but we need to upstream that to the SVG format once the format changes are settled), so the script could make the bounds check. It's not perfect, but it's simple. The template method would work just fine, too, no runtime checking needed.

**Comment by danngreen** [comment]
Closed: See #207
