### ISSUE TITLE
Link alt paramters to regular parameters and render to their context menu

### ISSUE THREAD

**Issue by LnnrtS** [4ms/metamodule#207]
> The data structure in the original branch had a field in the AltParam definition for the enum ID of a parameter it's attached to. Attaching to a control is the most common case (the Tapo might be the only exception). I could see some array of {param_id, alt_param_id} values from the Elem enum... since we have those values generated after the Elements array.

**Comment by danngreen** [comment]
Now that all modules are complete, I don't see a need for this. Alt Params are organized by their name, not by the associated control on the hardware version.
