### ISSUE TITLE
Support for minAngle maxAngle for knobs

### ISSUE THREAD

**Issue by hemmer** [4ms/metamodule#238]
I'm updating the Befaco modules for recent updates on VCV side. All going well, but for one case, the knob has a custom range for the knob:

```
auto p = createParamCentered<Davies1900hLargeLightGreyKnob>(mm2px(Vec(15.0, 67.275)), module, Voltio::SEMITONES_PARAM);
p->minAngle = -0.83 * M_PI;
p->maxAngle = M_PI; 
addParam(p);
```

Is this or can this be supported on the metamodule side? I can try to implement if you point me in the right direction. If not I can make the Befaco metamodule branch remove these lines.

**Comment by danngreen** [comment]
Note: while adding fields to Knob, we might want to add snap (boolean), units (string), base, multiplier, and offset to ParamElement.
