### ISSUE TITLE
GUI not updating display of controls after module changes its own value

### ISSUE THREAD

**Issue by scanner-darkly** [4ms/metamodule#324]
Orca's Heart V2 uses buttons (params configured with `configSwitch`) to select scale notes. There is also a knob that selects scale presets, and when a new preset is selected, it will [update button states accordingly](https://github.com/scanner-darkly/eightfold/blob/efef2a88c34bbab28b1bf26b21db5ff7f4f42b6b/src/SDOrcasHeartV2.cpp#L408) by using `setValue`:

`params[SCALE_1_PARAM + i].setValue(scalePresets[scaleAPreset][i]);`

The values are properly changed, but the UI is not reflecting the new button state. When I change the button state using the button itself, the new state is displayed properly.

Tested with a firmware built from https://github.com/4ms/metamodule/commit/a72859f8c5c6ec18ce389d1e378001c7fa441ab5

**Comment by danngreen** [comment]
This is now working in v2.0.0-dev-0:
https://github.com/4ms/metamodule/releases/tag/firmware-v2.0.0-dev-0

I'm closing it since it's done, even though not merged into main
