### ISSUE TITLE
Update Befaco collection to v2.7.1

### ISSUE THREAD

**Issue by hemmer** [4ms/metamodule#341]
It's been a while since Befaco for metamodule has been updated, I'll take a look. This adds:

* Burst
* Voltio
* Octaves
* MidiThingv2 (not to be added to metamodule)

Interesting both Octaves (polyphonic) and PonyVCO (which is now updated polyphonic in VCV) now fail to function (by fail to function, I mean just output a burst of sound then stop in the simulator). EvenVCO, which was always polyphonic, still works (so it's not a general polyphony / simd issue). I have the monophonic versions from development branch, but it'd be much more satisfying to work out the issue. Perhaps they use an unsupported simd function. I'll try myself, but if I struggle I may point you at relevant bits, unless this issue sounds familiar to you already!

**Comment by danngreen** [comment]
Merged! Will be in release v1.1
